version: 0.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
before_build:
- ps: Get-Content install\installscriptMemoNoteUnicode.iss
build:
  parallel: true
  verbosity: minimal
after_build:
- cmd: "cd\npackages\Tools.InnoSetup.5.5.6\tools\iscc "Install\installscriptMemoNoteUnicode.iss""
artifacts:
- path: Install\Installer\
deploy:
- provider: GitHub
  release: memo-v.0.0.2
  auth_token:
    secure: 8e2bc45ec27d8e87fe3256f84ae84a23b7851dfb
  on:
    branch: master
    configuration: Release
    appveyor_repo_tag: true