version: 0.0.{build}
before_build:
- ps: 
build:
  verbosity: minimal
after_build:
- cmd: packages\Tools.InnoSetup.5.5.6\tools\ISCC Install\installscriptMemoNoteUnicode.iss
artifacts:
- path: MemoNote\Install\Installer
  type: WebDeployPackage
deploy:
- provider: GitHub
  tag: memo-v0.0.0
  release: memo-v$(appveyor_build_version)
  description: Release from appveyor
  auth_token:
    secure: xIrGBqNeilnrDeNWj51TJbs8HuU15lD7R2xoyIa68Rwq/CSiyQS+Eaeudnkzwe82
  artifact: MemoNote\Install\Installer.zip
  draft: false
  prerelease: false
  skip_tags: true
  