version: 0.0.{build}
before_build:
- ps: >-
    cd C:\projects\memonotex

    $VerFromAssemblyInfo = get-content SharedAssemblyInfo.cs

    $InstallScript = get-content Install\installscriptMemoNoteUnicode.iss

    $VerFromAssemblyInfo[26][27]

    $i = 26

    $verString = ""

    do
    	{
    	$verString = $verString + $VerFromAssemblyInfo[26][$i]
    	$i = $i + 1
    	}
    while($VerFromAssemblyInfo[26][$i] -ne ')')

    Write-Host("AssemblyInfo version is: ")

    $verString

    Write-Host("ISS version is: ")

    $InstallScript[2]

    $InstallScript[2] = "#define Version " + $verString

    $InstallScript[2]

    $InstallScript | set-content Install\installscriptMemoNoteUnicode.iss

    Write-Host("Version was changed succes")
build:
  verbosity: minimal
after_build:
- cmd: packages\Tools.InnoSetup.5.5.6\tools\ISCC Install\installscriptMemoNoteUnicode.iss
artifacts:
- path: MemoNote\Install\Installer
  type: WebDeployPackage
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: Release from appveyor
  auth_token:
    secure: xIrGBqNeilnrDeNWj51TJbs8HuU15lD7R2xoyIa68Rwq/CSiyQS+Eaeudnkzwe82
  artifact: MemoNote\Install\Installer.zip
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
  