version: 0.0.{build}
before_build:
- ps: >-
    cd C:\projects\memonotex\MemoNote

    $VerFromAssemblyInfo = get-content SharedAssemblyInfo.cs

    $InstallScript = get-content Install\installscriptMemoNoteUnicode.iss

    $VerFromAssemblyInfo[27][30]

    $i = 31

    $verString = ""

    do
    	{
    	$verString = $verString + $VerFromAssemblyInfo[27][$i]
    	$i = $i + 1
    	}
    while($VerFromAssemblyInfo[27][$i] -ne ')')

    $verString

    $InstallScript[2]

    $InstallScript[2] = "#define Version " + $verString

    $InstallScript[2]

    $InstallScript | set-content Install\installscriptMemoNoteUnicode.iss
-cmd: dir C:\projects\memonotex\MemoNote\
build:
  verbosity: minimal
after_build:
- cmd: packages\Tools.InnoSetup.5.5.6\tools\ISCC Install\installscriptMemoNoteUnicode.iss
artifacts:
- path: MemoNote\Install\Installer
  type: WebDeployPackage
deploy:
- provider: GitHub
  tag: memo-v$(appveyor_build_version)
  release: memo-v$(appveyor_build_version)
  description: Release from appveyor
  auth_token:
    secure: xIrGBqNeilnrDeNWj51TJbs8HuU15lD7R2xoyIa68Rwq/CSiyQS+Eaeudnkzwe82
  artifact: MemoNote\Install\Installer.zip
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
  