version: 0.0.1.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
before_build:
- ps: Get-Content install\installscriptMemoNoteUnicode.iss
build:
  parallel: true
  verbosity: minimal
artifacts:
- path: Install\Installer\
